# Generated by Django 3.1.1 on 2020-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user'),
        ('posts', '0003_auto_20201014_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='postid',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='userid',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('userid', 'postid')},
        ),
    ]
