# Generated by Django 3.1.1 on 2020-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user'),
        ('posts', '0004_auto_20201014_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='postid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
