# Generated by Django 3.1.1 on 2020-10-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201015_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followeeid',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followerid',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
