# Generated by Django 3.1.1 on 2020-10-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tagname',)},
        ),
    ]
